/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sources": {
    /**
     * Get Sources
     * @description List available forecast energy sources.
     *
     * Returns the set of energy source types supported by the API. Use the `name` value
     * as the `{source}` path segment in all other v1 routes (e.g. `/v1/GB/solar/regions`).
     */
    get: operations["get_sources_sources_get"];
  };
  "/countries": {
    /**
     * Get Countries
     * @description List available countries with their full capability manifest.
     *
     * Returns one entry per country the API has data for. Each entry includes:
     *
     * - **region_types** — the region granularities available for that country (e.g. national,
     *   GSP), including the forecast models valid for each type.
     * - **generation_sources** — the observed-generation observers available (e.g.
     *   `pvlive_in_day`, `pvlive_day_after`).
     * - **capacity_kW** and **centroid** — installed capacity and geographic centre.
     *
     * Use the `country` value (e.g. `GB`, `NL`) as the `{country}` path segment in all other
     * v1 routes.
     */
    get: operations["get_countries_countries_get"];
  };
  "/{country}/{source}/region-types": {
    /**
     * Get Region Types
     * @description List available region types for a country and energy source.
     *
     * Region types define the geographic granularity at which forecasts and generation
     * data are available — for example `national` or `gsp` for Great Britain.
     *
     * Each entry includes:
     *
     * - **type** — the slug used as the `region_type` query parameter throughout the API.
     * - **level** — hierarchical depth (lower = coarser; 0 = national).
     * - **forecast_models** — the models available for that region type, with the model
     *   `name` used as the `model` parameter on forecast endpoints. The first listed model
     *   is the default.
     */
    get: operations["get_region_types__country___source__region_types_get"];
  };
  "/{country}/{source}/generation-sources": {
    /**
     * Get Generation Sources
     * @description List available observed-generation sources for a country and energy source.
     *
     * Generation sources represent the different observers that produce actual (measured)
     * generation data — for example PV_Live in-day estimates vs finalised day-after values.
     * Use the `name` field as the `observer` parameter on generation endpoints.
     */
    get: operations["get_generation_sources__country___source__generation_sources_get"];
  };
  "/{country}/{source}/regions": {
    /**
     * Get Country Regions
     * @description List regions for a country, optionally filtered by type, parent, and/or name.
     *
     * Filter behavior:
     * - No filters — returns every region across all configured region types.
     * - `region_type` — restricts results to one granularity level (e.g. `gsp`).
     * - `parent` — returns the direct children of the specified parent region.
     * - `name` — case-insensitive substring search across region names.
     */
    get: operations["get_country_regions__country___source__regions_get"];
  };
  "/{country}/{source}/regions/{region}": {
    /**
     * Get Region
     * @description Get details for a specific region.
     *
     * Returns a `RegionDetail` object with the region's name, type, installed
     * capacity, centroid, and any available metadata fields.
     */
    get: operations["get_region__country___source__regions__region__get"];
  };
  "/{country}/{source}/regions/{region}/forecast": {
    /**
     * Get Forecast
     * @description Get the solar generation forecast for a specific region.
     *
     * Returns a time series of forecast values — power in kW at 30-minute resolution —
     * along with model metadata (name, version, creation time, initialisation time).
     *
     * By default the window runs from **now** to **48 hours ahead**. Use `start_utc` /
     * `end_utc` to override. Historical data is available up to 1 year back.
     */
    get: operations["get_forecast__country___source__regions__region__forecast_get"];
  };
  "/{country}/{source}/regions/{region}/forecast/last-updated": {
    /**
     * Get Forecast Last Updated Timestamp
     * @description Return the creation time of the most recent forecast for a region.
     *
     * Queries the forecast within ±30 minutes of now and returns the `last_updated_utc`
     * of the most recent run. Useful for monitoring freshness or driving "last updated"
     * indicators in a UI.
     */
    get: operations["get_forecast_last_updated_timestamp__country___source__regions__region__forecast_last_updated_get"];
  };
  "/{country}/{source}/forecasts/snapshot": {
    /**
     * Get Forecasts at Timestamp
     * @description Get forecasts for all regions of a given type at a specific time.
     *
     * Returns a `ForecastSnapshot` — a single point in time with one forecast value per
     * region. Useful for rendering a map of forecast output across an entire country at
     * a glance.
     */
    get: operations["get_forecasts_at_time__country___source__forecasts_snapshot_get"];
  };
  "/{country}/{source}/forecasts/period": {
    /**
     * Get Forecasts for Period
     * @description Get forecasts for all (or selected) regions across a time window.
     *
     * Returns a `RegionForecastMatrix` — a compact columnar structure with a shared
     * `times` array and one `power_kW` series per region. Designed for efficiently
     * loading all-region forecast data for charts or grid-management tools in a single
     * request.
     *
     * This endpoint is served entirely from a pre-warmed cache (one key per region).
     * It does not make live data-platform calls per request. If the cache has not yet
     * been populated after startup, the endpoint returns **503** with a `Retry-After: 60`
     * header — retry after a minute. The cache covers a ±2-day window around now,
     * refreshed every 24 hours (or on demand via `POST /{country}/{source}/forecasts/refresh`).
     *
     * Time-window and region filtering are applied in-memory from the cached data.
     * This endpoint fetches only the default forecast model for the selected
     * country + region type.
     *
     * Model and horizon filters are **not** supported on this endpoint — use
     * `GET /{country}/{source}/regions/{region}/forecast` for per-region model selection.
     */
    get: operations["get_forecasts_period__country___source__forecasts_period_get"];
  };
  "/{country}/{source}/regions/{region}/generation": {
    /**
     * Get Generation
     * @description Get observed solar generation for a specific region.
     *
     * Returns a time series of measured generation values — power in kW — from the
     * specified observer. The default window is the **last 24 hours**; use `start_utc` /
     * `end_utc` to extend or shift it. Historical data is available up to 1 year back.
     *
     * Two observers are available for GB solar:
     *
     * - **pvlive_in_day** (default) — PV_Live in-day estimates, updated every 30 minutes.
     *   These are the most recent values but may be revised later.
     * - **pvlive_day_after** — PV_Live day-after final values, available from the following
     *   morning. Use these when accuracy is more important than latency.
     *
     * NL currently has one observer for solar:
     *
     * - **ned_nl** — NED NL estimated solar generation for provinces / national including curtailment.
     */
    get: operations["get_generation__country___source__regions__region__generation_get"];
  };
  "/{country}/{source}/generation/snapshot": {
    /**
     * Get Generation at Timestamp
     * @description Get observed generation for all regions of a given type at a specific time.
     *
     * Returns a `GenerationSnapshot` — a single point in time with one observed generation
     * value per region. Useful for rendering a map of current solar output across an entire
     * country.
     *
     * When `time_utc` is omitted the endpoint resolves the most recent available timestamp
     * automatically (looking back up to 6 hours) rather than using "now", which would
     * rarely have data.
     */
    get: operations["get_generation_at_timestamp__country___source__generation_snapshot_get"];
  };
  "/{country}/{source}/generation/period": {
    /**
     * Get Generation for Period
     * @description Get observed generation for all (or selected) regions across a time window.
     *
     * Returns a `RegionGenerationMatrix` — a compact columnar structure with a shared
     * `times` array and one `power_kW` series per region. Analogous to the forecast
     * period endpoint but for observed (actual) generation data.
     *
     * This endpoint is served entirely from a pre-warmed cache (one key per region).
     * It does not make live data-platform calls per request. If the cache has not yet
     * been populated after startup, the endpoint returns **503** with a `Retry-After: 60`
     * header — retry after a minute. The cache covers a ±2-day window around now,
     * refreshed every 24 hours (or on demand via `POST /{country}/{source}/generation/refresh`).
     *
     * Time-window and region filtering are applied in-memory from the cached data.
     */
    get: operations["get_generation_period__country___source__generation_period_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Centroid
     * @description Geographic centroid of a region.
     */
    Centroid: {
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
    };
    /**
     * CountryDetail
     * @description Full capability manifest for a country — region types, models, and generation sources.
     */
    CountryDetail: {
      /** Country */
      country: string;
      /** Name */
      name: string;
      /** Capacity Kw */
      capacity_kW: number;
      centroid: components["schemas"]["Centroid"];
      /**
       * Region Types
       * @default []
       */
      region_types?: components["schemas"]["RegionType"][];
      /**
       * Generation Sources
       * @default []
       */
      generation_sources?: components["schemas"]["GenerationSource"][];
    };
    /**
     * ForecastModel
     * @description A forecaster (model) available for a region type.
     */
    ForecastModel: {
      /** Name */
      name: string;
      /** Label */
      label: string;
    };
    /**
     * ForecastResponse
     * @description Forecast time series for a region, with shared metadata.
     */
    ForecastResponse: {
      /** Region Name */
      region_name: string;
      /** Capacity Kw */
      capacity_kW: number;
      /** Model Name */
      model_name?: string | null;
      /** Model Version */
      model_version?: string | null;
      /** Last Updated Utc */
      last_updated_utc?: string | null;
      /** Latest Init Utc */
      latest_init_utc?: string | null;
      /** Horizon Minutes */
      horizon_minutes?: number | null;
      /** Values */
      values: components["schemas"]["ForecastValue"][];
    };
    /**
     * ForecastSnapshot
     * @description Snapshot forecast across all regions at a single point in time.
     */
    ForecastSnapshot: {
      /**
       * Time Utc
       * Format: date-time
       */
      time_utc: string;
      /** Model Name */
      model_name?: string | null;
      /** Model Version */
      model_version?: string | null;
      /** Last Updated Utc */
      last_updated_utc?: string | null;
      /** Latest Init Utc */
      latest_init_utc?: string | null;
      /** Values */
      values: components["schemas"]["RegionForecastValue"][];
    };
    /**
     * ForecastValue
     * @description A single forecast value at a point in time.
     */
    ForecastValue: {
      /**
       * Time Utc
       * Format: date-time
       */
      time_utc: string;
      /** Power Kw */
      power_kW: number;
      /** Plevels Kw */
      plevels_kW?: {
        [key: string]: number;
      };
    };
    /**
     * GenerationResponse
     * @description Observed generation time series for a region, with shared metadata.
     */
    GenerationResponse: {
      /** Region Name */
      region_name: string;
      /** Capacity Kw */
      capacity_kW: number;
      /** Observer Name */
      observer_name?: string | null;
      /** Values */
      values: components["schemas"]["GenerationValue"][];
    };
    /**
     * GenerationSnapshot
     * @description Snapshot observed generation across all regions at a single point in time.
     */
    GenerationSnapshot: {
      /**
       * Time Utc
       * Format: date-time
       */
      time_utc: string;
      /** Observer Name */
      observer_name?: string | null;
      /** Values */
      values: components["schemas"]["RegionGenerationValue"][];
    };
    /**
     * GenerationSource
     * @description A generation (observation) source definition for a country.
     */
    GenerationSource: {
      /** Source */
      source: string;
      /** Name */
      name: string;
      /** Label */
      label: string;
    };
    /**
     * GenerationValue
     * @description A single observed generation value at a point in time.
     */
    GenerationValue: {
      /**
       * Time Utc
       * Format: date-time
       */
      time_utc: string;
      /** Power Kw */
      power_kW: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * RegionDetail
     * @description Detailed region information including metadata.
     */
    RegionDetail: {
      /** Name */
      name: string;
      /** Type */
      type?: string | null;
      /** Capacity Kw */
      capacity_kW: number;
      centroid: components["schemas"]["Centroid"];
      /** Metadata */
      metadata?: {
        [key: string]: string | number;
      };
    };
    /**
     * RegionForecast
     * @description Forecast time series for one region — used in matrix responses.
     */
    RegionForecast: {
      /** Region Name */
      region_name: string;
      /** Capacity Kw */
      capacity_kW: number;
      /** Power Kw */
      power_kW: number[];
      /** Plevels Kw */
      plevels_kW?: {
        [key: string]: number[];
      };
    };
    /**
     * RegionForecastMatrix
     * @description Forecast time series for all regions across a time window.
     */
    RegionForecastMatrix: {
      /** Model Name */
      model_name?: string | null;
      /** Model Version */
      model_version?: string | null;
      /** Last Updated Utc */
      last_updated_utc?: string | null;
      /** Latest Init Utc */
      latest_init_utc?: string | null;
      /** Cache Updated Utc */
      cache_updated_utc?: string | null;
      /** Times Utc */
      times_utc: string[];
      /** Regions */
      regions: components["schemas"]["RegionForecast"][];
    };
    /**
     * RegionForecastValue
     * @description A single forecast value for one region — used in snapshot responses.
     */
    RegionForecastValue: {
      /** Region Name */
      region_name: string;
      /** Capacity Kw */
      capacity_kW: number;
      /** Power Kw */
      power_kW: number;
      /** Plevels Kw */
      plevels_kW?: {
        [key: string]: number;
      } | null;
    };
    /**
     * RegionGeneration
     * @description Generation time series for one region — used in matrix responses.
     */
    RegionGeneration: {
      /** Region Name */
      region_name: string;
      /** Capacity Kw */
      capacity_kW: number;
      /** Power Kw */
      power_kW: number[];
    };
    /**
     * RegionGenerationMatrix
     * @description Observed generation time series for all regions across a time window.
     */
    RegionGenerationMatrix: {
      /** Observer Name */
      observer_name?: string | null;
      /** Cache Updated Utc */
      cache_updated_utc?: string | null;
      /** Times Utc */
      times_utc: string[];
      /** Regions */
      regions: components["schemas"]["RegionGeneration"][];
    };
    /**
     * RegionGenerationValue
     * @description A single observed generation value for one region — used in snapshot responses.
     */
    RegionGenerationValue: {
      /** Region Name */
      region_name: string;
      /** Capacity Kw */
      capacity_kW: number;
      /** Power Kw */
      power_kW: number;
    };
    /**
     * RegionType
     * @description A region type definition for a country.
     */
    RegionType: {
      /** Type */
      type: string;
      /** Label */
      label: string;
      /** Level */
      level: number;
      /** Default Model */
      default_model?: string | null;
      /**
       * Forecast Models
       * @default []
       */
      forecast_models?: components["schemas"]["ForecastModel"][];
    };
    /**
     * Source
     * @description An available forecast source (energy type).
     */
    Source: {
      /** Name */
      name: string;
      /** Label */
      label: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Get Sources
   * @description List available forecast energy sources.
   *
   * Returns the set of energy source types supported by the API. Use the `name` value
   * as the `{source}` path segment in all other v1 routes (e.g. `/v1/GB/solar/regions`).
   */
  get_sources_sources_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Source"][];
        };
      };
    };
  };
  /**
   * Get Countries
   * @description List available countries with their full capability manifest.
   *
   * Returns one entry per country the API has data for. Each entry includes:
   *
   * - **region_types** — the region granularities available for that country (e.g. national,
   *   GSP), including the forecast models valid for each type.
   * - **generation_sources** — the observed-generation observers available (e.g.
   *   `pvlive_in_day`, `pvlive_day_after`).
   * - **capacity_kW** and **centroid** — installed capacity and geographic centre.
   *
   * Use the `country` value (e.g. `GB`, `NL`) as the `{country}` path segment in all other
   * v1 routes.
   */
  get_countries_countries_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CountryDetail"][];
        };
      };
    };
  };
  /**
   * Get Region Types
   * @description List available region types for a country and energy source.
   *
   * Region types define the geographic granularity at which forecasts and generation
   * data are available — for example `national` or `gsp` for Great Britain.
   *
   * Each entry includes:
   *
   * - **type** — the slug used as the `region_type` query parameter throughout the API.
   * - **level** — hierarchical depth (lower = coarser; 0 = national).
   * - **forecast_models** — the models available for that region type, with the model
   *   `name` used as the `model` parameter on forecast endpoints. The first listed model
   *   is the default.
   */
  get_region_types__country___source__region_types_get: {
    parameters: {
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegionType"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Generation Sources
   * @description List available observed-generation sources for a country and energy source.
   *
   * Generation sources represent the different observers that produce actual (measured)
   * generation data — for example PV_Live in-day estimates vs finalised day-after values.
   * Use the `name` field as the `observer` parameter on generation endpoints.
   */
  get_generation_sources__country___source__generation_sources_get: {
    parameters: {
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GenerationSource"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Country Regions
   * @description List regions for a country, optionally filtered by type, parent, and/or name.
   *
   * Filter behavior:
   * - No filters — returns every region across all configured region types.
   * - `region_type` — restricts results to one granularity level (e.g. `gsp`).
   * - `parent` — returns the direct children of the specified parent region.
   * - `name` — case-insensitive substring search across region names.
   */
  get_country_regions__country___source__regions_get: {
    parameters: {
      query?: {
        /** @description Region type slug (e.g. 'gsp', 'national'). Valid values are country-specific — see `/{country}/{source}/region-types`. The enum lists all types across all countries. */
        region_type?: "gsp" | "national" | "province";
        /** @description List children of a specific parent region (name or `national`). */
        parent?: string | null;
        /** @description Filter by name (case-insensitive substring match). */
        name?: string | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegionDetail"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Region
   * @description Get details for a specific region.
   *
   * Returns a `RegionDetail` object with the region's name, type, installed
   * capacity, centroid, and any available metadata fields.
   */
  get_region__country___source__regions__region__get: {
    parameters: {
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
        /** @description Region identifier — `national`, or region_name (case-insensitive). Use `GET /{country}/{source}/regions` to browse available regions. */
        region: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegionDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Forecast
   * @description Get the solar generation forecast for a specific region.
   *
   * Returns a time series of forecast values — power in kW at 30-minute resolution —
   * along with model metadata (name, version, creation time, initialisation time).
   *
   * By default the window runs from **now** to **48 hours ahead**. Use `start_utc` /
   * `end_utc` to override. Historical data is available up to 1 year back.
   */
  get_forecast__country___source__regions__region__forecast_get: {
    parameters: {
      query?: {
        /** @description Start of window (UTC). */
        start_utc?: string | null;
        /** @description End of forecast window (UTC). Defaults to 48 hours from now. */
        end_utc?: string | null;
        /** @description Only include forecasts created at or before this time (UTC). Use to retrieve the forecast 'as it was' at a point in time. */
        creation_limit_utc?: string | null;
        /** @description Forecast horizon filter in minutes. For example, `60` returns only the 1-hour-ahead forecast value for each target timestep. */
        horizon_minutes?: number | null;
        model?:
          | (
              | "blend"
              | "blend_adjust"
              | "ecmwf_mo_sat_uncurtailed"
              | "ecmwf_mo_sat_uncurtailed_adjust"
              | "pvnet_day_ahead"
              | "pvnet_day_ahead_adjust"
              | "pvnet_ecmwf"
              | "pvnet_ecmwf_adjust"
              | "pvnet_intraday"
              | "pvnet_intraday_adjust"
              | "pvnet_sat"
              | "pvnet_sat_adjust"
              | "pvnet_ukv"
              | "pvnet_ukv_adjust"
            )
          | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
        /** @description Region identifier — `national`, or region_name (case-insensitive). Use `GET /{country}/{source}/regions` to browse available regions. */
        region: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ForecastResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Forecast Last Updated Timestamp
   * @description Return the creation time of the most recent forecast for a region.
   *
   * Queries the forecast within ±30 minutes of now and returns the `last_updated_utc`
   * of the most recent run. Useful for monitoring freshness or driving "last updated"
   * indicators in a UI.
   */
  get_forecast_last_updated_timestamp__country___source__regions__region__forecast_last_updated_get: {
    parameters: {
      query?: {
        model?:
          | (
              | "blend"
              | "blend_adjust"
              | "ecmwf_mo_sat_uncurtailed"
              | "ecmwf_mo_sat_uncurtailed_adjust"
              | "pvnet_day_ahead"
              | "pvnet_day_ahead_adjust"
              | "pvnet_ecmwf"
              | "pvnet_ecmwf_adjust"
              | "pvnet_intraday"
              | "pvnet_intraday_adjust"
              | "pvnet_sat"
              | "pvnet_sat_adjust"
              | "pvnet_ukv"
              | "pvnet_ukv_adjust"
            )
          | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
        /** @description Region identifier — `national`, or region_name (case-insensitive). Use `GET /{country}/{source}/regions` to browse available regions. */
        region: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Forecasts at Timestamp
   * @description Get forecasts for all regions of a given type at a specific time.
   *
   * Returns a `ForecastSnapshot` — a single point in time with one forecast value per
   * region. Useful for rendering a map of forecast output across an entire country at
   * a glance.
   */
  get_forecasts_at_time__country___source__forecasts_snapshot_get: {
    parameters: {
      query: {
        /** @description Region type slug (e.g. 'gsp', 'national'). Valid values are country-specific — see `/{country}/{source}/region-types`. The enum lists all types across all countries. */
        region_type: "gsp" | "national" | "province";
        model_name?:
          | (
              | "blend"
              | "blend_adjust"
              | "ecmwf_mo_sat_uncurtailed"
              | "ecmwf_mo_sat_uncurtailed_adjust"
              | "pvnet_day_ahead"
              | "pvnet_day_ahead_adjust"
              | "pvnet_ecmwf"
              | "pvnet_ecmwf_adjust"
              | "pvnet_intraday"
              | "pvnet_intraday_adjust"
              | "pvnet_sat"
              | "pvnet_sat_adjust"
              | "pvnet_ukv"
              | "pvnet_ukv_adjust"
            )
          | null;
        /** @description Forecast model version. */
        model_version?: string | null;
        /** @description Forecast target time (UTC). Defaults to now floored to 30 minutes. */
        time_utc?: string | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ForecastSnapshot"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Forecasts for Period
   * @description Get forecasts for all (or selected) regions across a time window.
   *
   * Returns a `RegionForecastMatrix` — a compact columnar structure with a shared
   * `times` array and one `power_kW` series per region. Designed for efficiently
   * loading all-region forecast data for charts or grid-management tools in a single
   * request.
   *
   * This endpoint is served entirely from a pre-warmed cache (one key per region).
   * It does not make live data-platform calls per request. If the cache has not yet
   * been populated after startup, the endpoint returns **503** with a `Retry-After: 60`
   * header — retry after a minute. The cache covers a ±2-day window around now,
   * refreshed every 24 hours (or on demand via `POST /{country}/{source}/forecasts/refresh`).
   *
   * Time-window and region filtering are applied in-memory from the cached data.
   * This endpoint fetches only the default forecast model for the selected
   * country + region type.
   *
   * Model and horizon filters are **not** supported on this endpoint — use
   * `GET /{country}/{source}/regions/{region}/forecast` for per-region model selection.
   */
  get_forecasts_period__country___source__forecasts_period_get: {
    parameters: {
      query: {
        /** @description Region type slug (e.g. 'gsp'). Only sub-national types are supported — national-level data is not pre-warmed. Valid values are country-specific — see `/{country}/{source}/region-types`. The enum lists all types across all countries. */
        region_type: "gsp" | "province";
        /** @description Start of window (UTC). Defaults to 2 days before now (floored to the nearest 6 hours). */
        start_utc?: string | null;
        /** @description End of window (UTC). Defaults to 2 days after now (floored to the nearest 6 hours). */
        end_utc?: string | null;
        /** @description Limit to specific region names (e.g. `?region_names=GSP1&region_names=GSP2`). */
        region_names?: string[] | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegionForecastMatrix"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Generation
   * @description Get observed solar generation for a specific region.
   *
   * Returns a time series of measured generation values — power in kW — from the
   * specified observer. The default window is the **last 24 hours**; use `start_utc` /
   * `end_utc` to extend or shift it. Historical data is available up to 1 year back.
   *
   * Two observers are available for GB solar:
   *
   * - **pvlive_in_day** (default) — PV_Live in-day estimates, updated every 30 minutes.
   *   These are the most recent values but may be revised later.
   * - **pvlive_day_after** — PV_Live day-after final values, available from the following
   *   morning. Use these when accuracy is more important than latency.
   *
   * NL currently has one observer for solar:
   *
   * - **ned_nl** — NED NL estimated solar generation for provinces / national including curtailment.
   */
  get_generation__country___source__regions__region__generation_get: {
    parameters: {
      query?: {
        /** @description The observer source name. */
        observer?: "ned_nl" | "pvlive_day_after" | "pvlive_in_day";
        /** @description Start of window (UTC). */
        start_utc?: string | null;
        /** @description End of generation window (UTC). Defaults to now. */
        end_utc?: string | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
        /** @description Region identifier — `national`, or region_name (case-insensitive). Use `GET /{country}/{source}/regions` to browse available regions. */
        region: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GenerationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Generation at Timestamp
   * @description Get observed generation for all regions of a given type at a specific time.
   *
   * Returns a `GenerationSnapshot` — a single point in time with one observed generation
   * value per region. Useful for rendering a map of current solar output across an entire
   * country.
   *
   * When `time_utc` is omitted the endpoint resolves the most recent available timestamp
   * automatically (looking back up to 6 hours) rather than using "now", which would
   * rarely have data.
   */
  get_generation_at_timestamp__country___source__generation_snapshot_get: {
    parameters: {
      query: {
        /** @description Region type slug (e.g. 'gsp', 'national'). Valid values are country-specific — see `/{country}/{source}/region-types`. The enum lists all types across all countries. */
        region_type: "gsp" | "national" | "province";
        /** @description The observer source name. */
        observer?: "ned_nl" | "pvlive_day_after" | "pvlive_in_day";
        /** @description Observation target time (UTC). Defaults to the most recent available timestamp within the last 6 hours. */
        time_utc?: string | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GenerationSnapshot"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Generation for Period
   * @description Get observed generation for all (or selected) regions across a time window.
   *
   * Returns a `RegionGenerationMatrix` — a compact columnar structure with a shared
   * `times` array and one `power_kW` series per region. Analogous to the forecast
   * period endpoint but for observed (actual) generation data.
   *
   * This endpoint is served entirely from a pre-warmed cache (one key per region).
   * It does not make live data-platform calls per request. If the cache has not yet
   * been populated after startup, the endpoint returns **503** with a `Retry-After: 60`
   * header — retry after a minute. The cache covers a ±2-day window around now,
   * refreshed every 24 hours (or on demand via `POST /{country}/{source}/generation/refresh`).
   *
   * Time-window and region filtering are applied in-memory from the cached data.
   */
  get_generation_period__country___source__generation_period_get: {
    parameters: {
      query: {
        /** @description Region type slug (e.g. 'gsp'). Only sub-national types are supported — national-level data is not pre-warmed. Valid values are country-specific — see `/{country}/{source}/region-types`. The enum lists all types across all countries. */
        region_type: "gsp" | "province";
        /** @description The observer source name. */
        observer?: "ned_nl" | "pvlive_day_after" | "pvlive_in_day";
        /** @description Start of window (UTC). Defaults to 2 days before now (floored to the nearest 6 hours). */
        start_utc?: string | null;
        /** @description End of window (UTC). Defaults to 2 days after now (floored to the nearest 6 hours). */
        end_utc?: string | null;
        /** @description Limit to specific region names (e.g. `?region_names=GSP1&region_names=GSP2`). */
        region_names?: string[] | null;
      };
      path: {
        /** @description The energy source type. Currently only 'solar' is supported. */
        source: "solar";
        /** @description Country code according to ISO 3166-1 alpha-2 codes, case insensitive. */
        country: "GB" | "NL";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegionGenerationMatrix"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
