import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>UX Demos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </>
  );
}
